Imported Upstream version 0.7.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,9 +4,13 @@
 # Ensure that we do not inherit these from env
 DEBUG=
 LIBDHCPCD=no
+WITH_DHCPCD_ONLINE=yes
 WITH_GTK=
+WITH_QT=
+WITH_ICONS=
 NOTIFY=yes
 INCLUDEDIR=
+UI=
 
 for x; do
 	opt=${x%%=*}
@@ -34,9 +38,14 @@ for x; do
 	--includedir) eval INCLUDEDIR="$INCLUDEDIR${INCLUDEDIR:+ }$var";;
 	--datadir|--infodir) ;; # ignore autotools
 	--disable-maintainer-mode|--disable-dependency-tracking) ;;
-	--icondir) ICONDIR=$var;;
+	--with-dhcpcd-online) WITH_DHCPCD_ONLINE=${var:-yes};;
+	--without-dhcpcd-online) WITH_DHCPCD_ONLINE=no;;
 	--with-gtk|--with-gtk+) WITH_GTK=${var:-yes};;
 	--without-gtk|--without-gtk+) WITH_GTK=no;;
+	--with-qt) WITH_QT=${var:-yes};;
+	--without-qt) WITH_QT=no;;
+	--with-icons) WITH_ICONS=${var:-yes};;
+	--without-icons) WITH_ICONS=no;;
 	--enable-notification) NOTIFY=yes;;
 	--disable-notification) NOTIFY=no;;
 	--help) echo "See the README file for available options"; exit 0;;
@@ -86,60 +95,48 @@ CONFIG_H=config.h
 CONFIG_MK=config.mk
 
 if [ -z "$BUILD" ]; then
-	BUILD=`uname -m`-unknown-`uname -s | tr '[:upper:]' '[:lower:]'`
+	# autoconf target triplet: cpu-vendor-os
+	BUILD=$(uname -m)-unknown-$(uname -s | tr '[:upper:]' '[:lower:]')
 fi
-if [ -z "$HOST" ]; then
-	[ -z "$TARGET" ] && TARGET=$BUILD
-	HOST=$TARGET
-fi
-if [ -z "$TARGET" ]; then
-	[ -z "$HOST" ] && HOST=$BUILD
-	TARGET=$HOST
-fi
+: ${HOST:=$BUILD}
 
-# Debian and Slackware have linux in different places when dealing with
-# autoconf, so we deal with that here.
 if [ -z "$OS" ]; then
-	case "$TARGET" in
-	*-linux-*|linux-*|*-linux|linux) OS=linux;;
+	echo "Deriving operating system from ... $HOST"
+	# Derive OS from cpu-vendor-[kernel-]os
+	CPU=${HOST%%-*}
+	REST=${HOST#*-}
+	if [ "$CPU" != "$REST" ]; then
+		VENDOR=${REST%%-*}
+		REST=${REST#*-}
+		if [ "$VENDOR" != "$REST" ]; then
+			# Use kernel if given, otherwise os
+			OS=${REST%%-*}
+		else
+			# 2 tupple
+			OS=$VENDOR
+			VENDOR=
+		fi
+	fi
+
+        # Work with cpu-kernel-os, ie Debian
+	case "$VENDOR" in
+	linux*|kfreebsd*) OS=$VENDOR; VENDOR= ;;
+	esac
+	# Special case
+	case "$OS" in
+	gnu*) OS=hurd;; # No HURD support as yet
 	esac
 fi
 
-if [ -z "$OS" ]; then
-	# Derive OS from cpu-manufacturer-os-kernel
-	CPU=${TARGET%%-*}
-	REST=${TARGET#*-}
-	if [ "$CPU" != "$REST" ]; then
-		MANU=${REST%%-*}
-		REST=${REST#*-}
-		if [ "$MANU" != "$REST" ]; then
-			OS=${REST%%-*}
-			REST=${REST#*-}
-			if [ "$OS" != "$REST" ]; then
-				KERNEL=${REST%%-*}
-			else
-				# 3 tupple
-				KERNEL=$OS
-				OS=$MANU
-				MANU=
-			fi
-		else
-			# 2 tupple
-			OS=$MANU
-			MANU=
-		fi
-	fi
-fi
-
-echo "Configuring dhcpcd-ui for ... $OS"
+echo "Configuring dhcpcd for ... $OS"
 rm -f $CONFIG_H $CONFIG_MK
 echo "# $OS" >$CONFIG_MK
 echo "/* $OS */" >$CONFIG_H
 
 VERSION=$($SED -ne 's/VERSION=	//p' Makefile)
-echo "#define VERSION \"$VERSION\"" >>$CONFIG_H
+echo "#define VERSION		\"$VERSION\"" >>$CONFIG_H
 
-for x in PREFIX SYSCONFDIR BINDIR ICONDIR; do
+for x in PREFIX SYSCONFDIR BINDIR; do
 	eval v=\$$x
 	# Make files look nice for import
 	l=$((10 - ${#x}))
@@ -150,68 +147,132 @@ for x in PREFIX SYSCONFDIR BINDIR ICONDIR; do
 	[ $l -gt 2 ] && t="	"
 	echo "#define $x$t	\"$v\"" >>$CONFIG_H
 done
-echo "MANDIR=		${MANDIR}" >>$CONFIG_MK
+echo "#define ICONDIR		\"$ICONDIR\"" >>$CONFIG_H
+echo "MANDIR=		$MANDIR" >>$CONFIG_MK
 
-if [ -z "$CC" ]; then
-	printf "Looking for compiler ... "
-	for b in $TARGET- ""; do
-		for cc in gcc clang pcc icc cc; do
-			if type $b$cc >/dev/null 2>&1; then
-				CC=$b$cc
-				echo "$CC"
-				break
-			fi
-		done
-		[ -n "$CC" ] && break
-	done
-	if [ -z "$CC" ]; then
-		echo
-		echo "no suitable compiler found - aborting" >&2
-		exit 1
-	fi
+# Always obey CC.
+# However, if CC is not specified and we are given GNU style
+# --host or --build targets the expectation is we try and match that
+# to a compiler.
+if [ -n "$CC" ]; then
+	HOSTCC=
 else
-	echo "Using compiler $CC"
+	CC=cc
+	_COMPILERS="cc clang gcc pcc icc"
 fi
-echo "CC=		$CC" >>$CONFIG_MK
+if [ -n "$HOSTCC" ]; then
+	for _CC in $_COMPILERS; do
+		_CC=$(_which "$HOSTCC$_CC")
+		if [ -x "$_CC" ]; then
+			CC=$_CC
+			break
+		fi
+	done
+fi
+if ! type "$CC" >/dev/null 2>&1; then
+	for _CC in $_COMPILERS; do
+		_CC=$(_which "$_CC")
+		if [ -x "$_CC" ]; then
+			CC=$_CC
+			break
+		fi
+	done
+fi
 
-if [ -z "$CFLAGS" ]; then
-	CFLAGS="-O2"
+echo "Using compiler .. $CC"
+cat <<EOF >_test.c
+int main(void) {
+	return 0;
+}
+EOF
+_CC=false
+if $CC _test.c -o _test >/dev/null 2>&1; then
+	[ -x _test ] && _CC=true
 fi
-echo "CFLAGS=		$CFLAGS" >>$CONFIG_MK
-if [ -n "$CPPLAGS" ]; then
-	echo "CPPLAGS=		$CPPLAGS" >>$CONFIG_MK
+rm -f _test.c _test
+if ! $_CC; then
+	echo "$CC does not create executables"
+	exit 1
 fi
+[ "$CC" != cc ] && echo "CC=	$CC" >>$CONFIG_MK
+$CC --version | $SED -e '1!d'
+
+# Set to blank, then append user config
+# We do this so our SED call to append to XCC remains portable
+if [ -n "$CFLAGS" ]; then
+	echo "CFLAGS=" >>$CONFIG_MK
+	echo "CFLAGS+=	$CFLAGS" >>$CONFIG_MK
+fi
+if [ -n "$CPPFLAGS" ]; then
+	echo "CPPFLAGS=" >>$CONFIG_MK
+	echo "CPPFLAGS+=	$CPPFLAGS" >>$CONFIG_MK
+fi
+if [ -n "$LDFLAGS" ]; then
+	echo "LDFLAGS=" >>$CONFIG_MK
+	echo "LDFLAGS+=	$LDFLAGS" >>$CONFIG_MK
+fi
+
 for x in $INCLUDEDIR; do
 	echo "CPPFLAGS+=	-I$x" >>$CONFIG_MK
 done
 
-if [ -n "$DEBUG" -a "$DEBUG" != no -a "$DEBUG" != false ]; then
-	echo "Enabling memory debugging"
-	echo "CPPFLAGS+=	-DDEBUG_MEMORY" >>$CONFIG_MK
-elif [ -z "$DEBUG" -a -d .git ]; then
-	printf "Found git ... "
+if [ -z "$DEBUG" -a -f .fslckout ]; then
+	printf "Found fossil checkout ... "
 	DEBUG=yes
-	echo "LDADD+=		-Wl,-rpath=../libdhcpcd" >>$CONFIG_MK
 else
 	DEBUG=no
 fi
 if [ "$DEBUG" != no -a "$DEBUG" != false ]; then
 	echo "Adding debugging CFLAGS"
 	cat <<EOF >>$CONFIG_MK
-CFLAGS+=	-Wall -Wextra -Wimplicit -Wshadow -Wformat=2
+CFLAGS+=	-g -Wall -Wextra -Wshadow -Wformat=2
 CFLAGS+=	-Wmissing-prototypes -Wmissing-declarations
 CFLAGS+=	-Wmissing-noreturn -Wmissing-format-attribute
-CFLAGS+=	-Wredundant-decls  -Wnested-externs
+CFLAGS+=	-Wnested-externs
 CFLAGS+=	-Winline -Wwrite-strings -Wcast-align -Wcast-qual
-CFLAGS+=	-Wpointer-arith
-CFLAGS+=	-Wdeclaration-after-statement -Wsequence-point
-CFLAGS+=	-fno-common
+CFLAGS+=	-Wpointer-arith -Wstrict-overflow
+CFLAGS+=	-Wdeclaration-after-statement
+CFLAGS+=	-Wconversion
 EOF
+	case "$OS" in
+	mirbsd*|openbsd*);; # OpenBSD has many redundant decs in system headers
+	*)		echo "CFLAGS+=	-Wredundant-decls" >>$CONFIG_MK;;
+	esac
+else
+	# Disable assertations
+	echo "CFLAGS+=	-DNDEBUG" >>$CONFIG_MK
 fi
 
 # Add CPPFLAGS and CFLAGS to CC for testing features
 XCC="$CC `$SED -n -e 's/CPPLAGS+=*\(.*\)/\1/p' $CONFIG_MK`"
 XCC="$XCC `$SED -n -e 's/CFLAGS+=*\(.*\)/\1/p' $CONFIG_MK`"
+
+if [ -z "$GETTEXT" ]; then
+	printf "Testing for gettext ... "
+	cat <<EOF >_gettext.c
+#include <libintl.h>
+int main(void) {
+	gettext("foo");
+	return 0;
+}
+EOF
+	LIB_INTL=
+	if $XCC _gettext.c -o _gettext 2>/dev/null; then
+		GETTEXT=yes
+	elif $XCC _gettext.c -o _gettext -lintl 2>/dev/null; then
+		GETTEXT="yes (-lintl)"
+		LIB_INTL=-lintl
+		QMAKE_CONFIG="CONFIG+=has_libintl"
+	else
+		GETTEXT=no
+	fi
+	echo "$GETTEXT"
+	rm -f _gettext.c _gettext
+fi
+if [ "$GETTEXT" != no ]; then
+	echo "#define HAS_GETTEXT" >>$CONFIG_H
+	echo "LIB_INTL=	$LIB_INTL" >>$CONFIG_MK
+fi
 
 if [ -z "$STRLCPY" ]; then
 	printf "Testing for strlcpy ... "
@@ -233,8 +294,9 @@ EOF
 	rm -f _strlcpy.c _strlcpy
 fi
 if [ "$STRLCPY" = no ]; then
-	echo "#define strlcpy(dst, src, n) snprintf(dst, n, \"%s\", src)" \
-	>>$CONFIG_H
+	echo "#define strlcpy(dst, src, n) " \
+	    "((size_t)snprintf(dst, n, \"%s\", src))" \
+	    >>$CONFIG_H
 fi
 
 if [ -z "$LIBDIR" ]; then
@@ -262,19 +324,23 @@ echo "LIB_DHCPCD=	$x" >>$CONFIG_MK
 
 # Due to our use of pkg-config, pass --as-needed to ld so we only link
 # what we actually need.
-echo "LDADD+=	-Wl,--as-needed" >>$CONFIG_MK
+echo "LDADD+=		-Wl,--as-needed" >>$CONFIG_MK
 
-# Get DBus CFLAGS
-DBUS_CFLAGS=$(pkg-config --cflags dbus-1) || exit 1
-DBUS_LIBS=$(pkg-config --libs dbus-1) || exit 1
-echo "DBus CFLAGS=$DBUS_CFLAGS"
-echo "DBus LIBS=$DBUS_LIBS"
-echo "DBUS_CFLAGS=	$DBUS_CFLAGS" >>$CONFIG_MK
-echo "DBUS_LIBS=	$DBUS_LIBS" >>$CONFIG_MK
-
-UI=
 if [ "$WITH_GTK" = yes -o -z "$WITH_GTK" ]; then
-	PKG="dbus-1 gtk+-2.0"
+	if pkg-config --cflags gtk+-2.0 >/dev/null 2>&1; then
+		WITH_GTK="gtk+-2.0"
+	elif pkg-config --cflags gtk+-3.0 >/dev/null 2>&1; then
+		WITH_GTK="gtk+-3.0"
+	fi
+elif [ -n "$WITH_GTK" -a "$WITH_GTK" != no ]; then
+	if ! pkg-config --cflags $WITH_GTK >/dev/null; then
+		echo "$0: no suitable GTK+ library has been found" >&2
+		exit 1
+	fi
+fi
+	
+if [ -n "$WITH_GTK" -a "$WITH_GTK" != no ]; then
+	PKG="$WITH_GTK"
 	if [ "$NOTIFY" = yes ]; then
 		PKG="$PKG${PKG:+ }libnotify"
 		echo "NOTIFY=		-DNOTIFY" >>$CONFIG_MK
@@ -290,11 +356,33 @@ if [ "$WITH_GTK" = yes -o -z "$WITH_GTK" ]; then
 	UI="$UI${UI:+ }dhcpcd-gtk"
 fi
 
-if [ -z "$UI" ]; then
-	echo "no UI is available, not building." >&2
-	exit 1
+DHCPCD_QT=false
+if [ "WITH_QT" = yes -o -z "$WITH_QT" ]; then
+	if type qmake >/dev/null 2>&1; then
+		UI="$UI${UI+ }dhcpcd-qt"
+		DHCPCD_QT=true
+	fi
+elif [ -n "$WITH_QT" -a "$WITH_QT" != no ]; then
+	if type qmake >/dev/null 2>&1; then
+		UI="$UI${UI+ }dhcpcd-qt"
+		DHCPCD_QT=true
+	else
+		echo "$0: no suitable QT library has been found" >&2
+		exit 1
+	fi
 fi
-echo "UI=		$UI" >>config.mk
+
+if [ -n "$UI" -a -z "$WITH_ICONS" ]; then
+	WITH_ICONS=yes
+fi
+if [ "$WITH_ICONS" = yes ]; then
+	echo "MKICONS=	icons" >>$CONFIG_MK
+fi
+
+if [ -n "$WITH_DHCPCD_ONLINE" -a "$WITH_DHCPCD_ONLINE" != no ]; then
+	UI="dhcpcd-online${UI:+ }$UI"
+fi
+echo "UI=		${UI:+libdhcpcd }$UI" >>$CONFIG_MK
 
 echo
 echo "   SYSCONFDIR =		$SYSCONFDIR"
@@ -306,3 +394,11 @@ echo "   UI =			$UI"
 echo
 
 echo "MKDIR=		\${TOPDIR}/mk" >>$CONFIG_MK
+
+if $DHCPCD_QT; then
+	QMAKE_CONFIG="$QMAKE_CONFIG PREFIX=$PREFIX MANDIR=$MANDIR"
+	if ! (cd src/dhcpcd-qt; qmake $QMAKE_CONFIG dhcpcd-qt.pro); then
+		echo "$0: failed to configure dhcpcd-qt" >&2
+		exit 1
+	fi
+fi
